; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .

[env:gpio_test]
platform = atmelavr
board = uno
framework = arduino

build_flags =
    -DPEDL_PLATFORM_AVR
    -I01_core
    -I02_drivers
    -I03_platform
    -I04_utils

build_src_filter =
    +<src/>
    +<02_drivers/>
    +<03_platform/>
    +<04_utils/>
    +<05_apps/gpio_test/>